name: authentication_private
description: A private packagee for user authentication.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  authentication_public:
    path: ../authentication_public
  equatable: ^2.0.3
  firebase_auth: ^3.3.4
  flutter:
    sdk: flutter
  given_when_then: ^0.2.0
  google_sign_in: ^5.2.1
  mocktail: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

