name: smack_talking_scoreboard_v2
description: An app to help you keep score and talk smak

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.5
  fake_cloud_firestore: ^1.2.0
  firebase_core: ^1.10.6
  flutter:
    sdk: flutter
  given_when_then: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/