name: smack_talking_scoreboard_v2
description: An app to help you keep score and talk smak

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  authentication_private:
    path: ../authentication_private
  authentication_public:
    path: ../authentication_public
  bloc_test: ^9.0.2
  cloud_firestore: ^3.1.5
  equatable: ^2.0.3
  fake_cloud_firestore: ^1.2.0
  firebase_core: ^1.10.6
  firestore_private:
    path: ../firestore_private
  firestore_public:
    path: ../firestore_public
  flow_builder: ^0.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  given_when_then: ^0.2.0
  result_type: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/