name: authentication_public
description: The publicly consumable authentication package.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  authentication_private:
    path: ../authentication_private
  formz: ^0.4.1
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  font_awesome_flutter: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0